export const data = [
  {
    id: '1',
    name: 'Dahi Raita',
    description: 'Fresh curd mixed with special spices.',
    current_Price: 40,
    original_Price: 60,
    offer: 20,
    category: 'Veg',
    subCategory: 'Dahi Salad',
    image: require('./assets/food1.jpg'),
    rating: {stars: 4.5, view: 1400},
  },
  {
    id: '2',
    name: 'Paneer Butter Masala',
    description: 'Rich creamy tomato-based curry with soft paneer cubes.',
    current_Price: 180,
    original_Price: 220,
    offer: 18,
    category: 'Veg',
    subCategory: 'Main Course',
    image: require('./assets/food2.jpg'),
    rating: {stars: 4.7, view: 2500},
  },
  {
    id: '3',
    name: 'Chicken Biryani',
    description: 'Spiced basmati rice cooked with marinated chicken.',
    current_Price: 250,
    original_Price: 300,
    offer: 17,
    category: 'Non-Veg',
    subCategory: 'Rice & Biryani',
    image: require('./assets/food3.jpg'),
    rating: {stars: 4.8, view: 5000},
  },
  {
    id: '4',
    name: 'Aloo Paratha',
    description: 'Stuffed wheat flatbread with spiced mashed potatoes.',
    current_Price: 60,
    original_Price: 80,
    offer: 25,
    category: 'Veg',
    subCategory: 'Breakfast',
    image: require('./assets/food4.jpg'),
    rating: {stars: 4.6, view: 1200},
  },
  {
    id: '5',
    name: 'Cold Coffee',
    description: 'Chilled creamy coffee blended with ice and chocolate syrup.',
    current_Price: 90,
    original_Price: 110,
    offer: 15,
    category: 'Beverage',
    subCategory: 'Drinks',
    image: require('./assets/food5.jpg'),
    rating: {stars: 4.4, view: 1800},
  },
  {
    id: '6',
    name: 'Masala Dosa',
    description: 'Crispy dosa stuffed with spicy mashed potatoes.',
    current_Price: 70,
    original_Price: 90,
    offer: 22,
    category: 'Veg',
    subCategory: 'South Indian',
    image: require('./assets/food1.jpg'),
    rating: {stars: 4.6, view: 1600},
  },
  {
    id: '7',
    name: 'Veg Pulao',
    description: 'Basmati rice cooked with mixed vegetables & spices.',
    current_Price: 130,
    original_Price: 160,
    offer: 18,
    category: 'Veg',
    subCategory: 'Rice & Biryani',
    image: require('./assets/food2.jpg'),
    rating: {stars: 4.5, view: 1400},
  },
  {
    id: '8',
    name: 'Butter Chicken',
    description: 'Creamy butter tomato-based chicken curry.',
    current_Price: 270,
    original_Price: 320,
    offer: 15,
    category: 'Non-Veg',
    subCategory: 'Main Course',
    image: require('./assets/food3.jpg'),
    rating: {stars: 4.9, view: 5500},
  },
  {
    id: '9',
    name: 'Chole Bhature',
    description: 'Spicy chickpea curry served with deep-fried bread.',
    current_Price: 90,
    original_Price: 120,
    offer: 20,
    category: 'Veg',
    subCategory: 'North Indian',
    image: require('./assets/food4.jpg'),
    rating: {stars: 4.7, view: 1900},
  },
  {
    id: '10',
    name: 'Mango Shake',
    description: 'Refreshing mango shake blended with fresh milk.',
    current_Price: 80,
    original_Price: 100,
    offer: 20,
    category: 'Beverage',
    subCategory: 'Drinks',
    image: require('./assets/food5.jpg'),
    rating: {stars: 4.3, view: 1700},
  },
  {
    id: '11',
    name: 'Rajma Chawal',
    description: 'Kidney bean curry served with steamed rice.',
    current_Price: 100,
    original_Price: 130,
    offer: 23,
    category: 'Veg',
    subCategory: 'North Indian',
    image: require('./assets/food1.jpg'),
    rating: {stars: 4.6, view: 1500},
  },
  {
    id: '12',
    name: 'Mutton Curry',
    description: 'Slow-cooked mutton in a rich spicy gravy.',
    current_Price: 300,
    original_Price: 350,
    offer: 14,
    category: 'Non-Veg',
    subCategory: 'Main Course',
    image: require('./assets/food2.jpg'),
    rating: {stars: 4.8, view: 4800},
  },
  {
    id: '13',
    name: 'Veg Manchurian',
    description: 'Crispy veg balls tossed in a spicy Chinese sauce.',
    current_Price: 110,
    original_Price: 140,
    offer: 21,
    category: 'Veg',
    subCategory: 'Chinese',
    image: require('./assets/food3.jpg'),
    rating: {stars: 4.5, view: 2000},
  },
  {
    id: '14',
    name: 'Tandoori Chicken',
    description: 'Grilled chicken marinated in yogurt & spices.',
    current_Price: 260,
    original_Price: 310,
    offer: 16,
    category: 'Non-Veg',
    subCategory: 'Starter',
    image: require('./assets/food4.jpg'),
    rating: {stars: 4.9, view: 5300},
  },
  {
    id: '15',
    name: 'Spring Roll',
    description: 'Crispy rolls stuffed with vegetables & spices.',
    current_Price: 90,
    original_Price: 120,
    offer: 20,
    category: 'Veg',
    subCategory: 'Snacks',
    image: require('./assets/food5.jpg'),
    rating: {stars: 4.4, view: 1500},
  },
  {
    id: '16',
    name: 'Dal Tadka',
    description: 'Yellow lentils tempered with ghee & spices.',
    current_Price: 80,
    original_Price: 100,
    offer: 18,
    category: 'Veg',
    subCategory: 'Main Course',
    image: require('./assets/food1.jpg'),
    rating: {stars: 4.7, view: 2200},
  },
  {
    id: '17',
    name: 'Fish Curry',
    description: 'Tangy & spicy fish curry with coconut base.',
    current_Price: 290,
    original_Price: 340,
    offer: 15,
    category: 'Non-Veg',
    subCategory: 'Main Course',
    image: require('./assets/food2.jpg'),
    rating: {stars: 4.6, view: 2700},
  },
  {
    id: '18',
    name: 'Paneer Tikka',
    description: 'Grilled paneer cubes marinated in spices.',
    current_Price: 150,
    original_Price: 190,
    offer: 21,
    category: 'Veg',
    subCategory: 'Starter',
    image: require('./assets/food3.jpg'),
    rating: {stars: 4.8, view: 3500},
  },
  {
    id: '19',
    name: 'Mixed Fruit Juice',
    description: 'Refreshing juice with mixed seasonal fruits.',
    current_Price: 100,
    original_Price: 130,
    offer: 23,
    category: 'Beverage',
    subCategory: 'Drinks',
    image: require('./assets/food4.jpg'),
    rating: {stars: 4.4, view: 1900},
  },
  {
    id: '20',
    name: 'Chocolate Ice Cream',
    description: 'Rich & creamy chocolate ice cream.',
    current_Price: 80,
    original_Price: 100,
    offer: 20,
    category: 'Dessert',
    subCategory: 'Ice Cream',
    image: require('./assets/food5.jpg'),
    rating: {stars: 4.7, view: 2500},
  },
];

export const menu_list = [
  {
    menu_name: "Dahi & Salad",
   // menu_image: menu_1,
  },
  {
    menu_name: "Chinese Starter",
   // menu_image: menu_2,
  },
  {
    menu_name: "Soup",
   // menu_image: menu_3,
  },
  {
    menu_name: "Chicken Sauce",
   // menu_image: menu_4,
  },
  {
    menu_name: "Noodles",
   // menu_image: menu_5,
  },
  {
    menu_name: "Fried Rice",
   // menu_image: menu_6,
  },
  {
    menu_name: "Veg Sauce",
   // menu_image: menu_7,
  },
  {
    menu_name: "Prawns",
   // menu_image: menu_8,
  },
  {
    menu_name: "Tandoori Dry",
   // menu_image: menu_9,
  },
  {
    menu_name: "Chicken Gravy",
    //menu_image: menu_10,
  },
  {
    menu_name: "Egg",
    //menu_image: menu_11,
  },
  {
    menu_name: "Mutton Gravy",
    //menu_image: menu_12,
  },
  {
    menu_name: "Paneer",
    //menu_image: menu_13,
  },
  {
    menu_name: "Vegetable",
    //menu_image: menu_14,
  },
  {
    menu_name: "Roti",
    //menu_image: menu_15,
  },
  {
    menu_name: "Biryani Pulao",
    //menu_image: menu_16,
  },
  {
    menu_name: "Thali",
    //menu_image: menu_17,
  },
  {
    menu_name: "Dessert",
    //menu_image: menu_18,
  },
];
